CREATE TABLE notices (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    title VARCHAR(150) NOT NULL,
    message TEXT NOT NULL,
    priority VARCHAR(10) NOT NULL CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH')),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);